all:
  hosts:
    srvk8sm01:
      ansible_host: 172.16.208.1
      ip: 172.16.208.1
      access_ip: 172.16.208.1
    srvk8sm02:
      ansible_host: 172.16.208.2
      ip: 172.16.208.2
      access_ip: 172.16.208.2
    srvk8sm03:
      ansible_host: 172.16.208.3
      ip: 172.16.208.3
      access_ip: 172.16.208.3
    srvk8sw01:
      ansible_host: 172.16.208.5
      ip: 172.16.208.5
      access_ip: 172.16.208.5
    srvk8sw02:
      ansible_host: 172.16.208.6
      ip: 172.16.208.6
      access_ip: 172.16.208.6
    srvk8sb01:
      ansible_host: 172.16.208.4
      ip: 172.16.208.4
      access_ip: 172.16.208.4
  children:
    kube_control_plane:
      hosts:
        srvk8sm01:
        srvk8sm02:
        srvk8sm03:
    kube_node:
      hosts:
        srvk8sw01:
        srvk8sw02:
    etcd:
      hosts:
        srvk8sm01:
        srvk8sm02:
        srvk8sm03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
